config/routes.rb
SampleBbs::Application.routes.draw do
  resources :topics, path: '/' do
    resources :comments
  end

  root to: 'topics#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic

  validates :name, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :comments

  validates :subject, presence: true, length: { maximum: 140 }
  validates :name, presence: true, length: { maximum: 20 }
  validates :body, presence: true

  paginates_per 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  def index
    @comments = @topic.comments
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = @topic.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = @topic.comments.build(comment_params)

    if @comment.save
      redirect_to @topic, notice: 'Comment was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to [@topic, @comment], notice: 'Comment was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to topic_comments_url(@topic), notice: 'Comment was successfully destroyed.'
  end

  private
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = @topic.comments.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def comment_params
    params.require(:comment).permit(:name, :content, :topic_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  def index
    @topics = Topic.order('created_at DESC').page params[:page]
    @topic = Topic.new
  end

  # GET /topics/1
  def show
    @comment = @topic.comments.build
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /topics/1
  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /topics/1
  def destroy
    @topic.destroy
    redirect_to topics_url, notice: 'Topic was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def topic_params
      params.require(:topic).permit(:subject, :name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@topic, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="comment_form">
  <div class="field">
    <!-- <%= f.label :name %><br> -->
    <%= f.text_field :name, :placeholder => "name", :size => "15" %>
  </div>
  <div class="field">
    <!-- <%= f.label :content %><br> -->
    <%= f.text_field :content, :placeholder => "content", :size => "40" %>
  </div>
  <div class="actions ">
    <%= f.submit :class => "btn" %>
  </div>
</div>
<% end %>

app/views/comments/_index.html.erb
<h2>Comments</h2>

<ul>
  <% if @topic.comments.size < 2 %>
    <li>No comments.</li>
  <% else %>
    <% @topic.comments.each do |comment| %>
      <% unless comment.id.nil? %>
        <li><%= comment.name %>: <%= comment.content %>(<%= comment.created_at.to_s(:db) %>)</li>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@topic, @comment] %> |
<%= link_to 'Back', topic_comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', topic_comment_path(@topic, comment) %></td>
        <td><%= link_to 'Edit', edit_topic_comment_path(@topic, comment) %></td>
        <td><%= link_to 'Destroy', topic_comment_path(@topic, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', topic_path(@topic) %> |
<%= link_to 'New Comment', new_topic_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', topic_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_topic_comment_path %> |
<%= link_to 'Back', topic_comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SUSHI-WAVE</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to "SUSHI-WAVE", topics_path %></h1>
<div class="wrapper">
  <%= yield %>
</div>
</body>
</html>

app/views/topics/_form.html.erb
<div class="form_wrap">
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :subject, :placeholder => "subject", :class => "nodes", :size => "50" %>

  </div>
  <div class="field">
    <%= f.text_field :name,:placeholder => "name",:class => "nodes", :size => "50" %>

  </div>
  <div class="field">
    <%= f.text_area :body,:size => "50x10" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn" %>
  </div>
<% end %>
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'topics/form' %>
<!-- <h>Listing topics</h2> -->
        <div class="box">
<dl>
  <% @topics.each do |topic| %>
  <div class="entry">
    <dt><strong><%= link_to topic.subject, topic %></strong> ///// <%= topic.name %> (<%= topic.created_at.to_s(:db) %>)</dt>
    <dd><%= simple_format topic.body %></dd>
</div>
  <% end %>
</dl>

<%= paginate @topics %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<div class="box">
  <div class="race">
<p>
  <strong>Subject:</strong>
  <%= @topic.subject %>
</p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <%= simple_format @topic.body %>
</p>

<%= render 'comments/index' %>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Delete', @topic, method: :delete, data: { confirm: 'Are you sure?'} %> |
<%= link_to 'Back', topics_path %>
</div>
</div>